Выполнение второго задания
htmlacademy-vue/17030-pizza-1 pull request #2
Opened 2021-07-11 10:00 UTC by corvus-007

2021-07-11 13:08 UTC, Djaler requested changes

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          v-for="filling in preferredFillings"
если один ингредиент добавлен в пиццу несколько раз, то должно рендериться соответствующее количество дивов. сейчас получается так, что второй заменяет первый, третий заменяет второй.

пересмотрел ТЗ по этому поводу. неочевидно написано, но мне кажется, что логичнее всё-таки тот вариант, который я описал. но можешь уточнить по этому поводу у авторов

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          v-for="filling in preferredFillings"
также, нужно чтобы сразу были выбраны толщина теста, размер пиццы и соус. Потому что иначе некорректно отображается просмотр пиццы

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        :value="doughItem"
это, конечно, работает, но мне кажется не очень красивым, что в итоге в dom у нас value у input - это объект.
Предлагаю сделать следующим образом - в качестве значения будет передаваться doughItem.type. А потом уже в вотчере будет по выбранному type из списка искаться объект dough (хотя, это можно сделать и снаружи BuilderDoughSelector)

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              v-model.number="fillingItem.count"
тут происходит изменение объекта, переданного в компонент через props. Это не очень хорошо, нужно явно бросать событие наверх и там менять данные

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/common/components/AppDrop.vue
> +        if (transferData.count < APP_COUNTER_MAX_VALUE) {
нехорошо, что этот общий компонент что-то знает о конкретном требовании другого компонента (ограничение по количеству). Думаю, это стоит обрабатывать на стороне AppDrag - блокировать саму возможность сделать drag по условию, переданному ему снаружи

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/common/components/AppCounter.vue
> +    min: {
не используются эти пропсы

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/common/components/AppRadio.vue
> +export default {
не используется

2021-07-11 13:08 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      fillings: pizza.ingredients.map((ingredient) =>
ну и нехорошо тут получается, что в этой переменной у нас хранятся, по сути, и исходные данные, которые нужно просто для отображения списка ингредиентов, и данные о выбранных (count). лучше это всё-таки сделать отдельно

2021-07-12 11:39 UTC, corvus-007 commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        :value="doughItem"
Я тогда так сделаю и для выбора размера и соуса. А то я там тоже передавал объекты ☺

2021-07-12 12:21 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        :value="doughItem"
да, конечно. я просто не стал дублировать

2021-07-13 17:16 UTC, corvus-007 commented on src/frontend/src/common/components/AppRadio.vue
> +export default {
Пока не понял, что именно не используется. Компонент? Если компонент, то я его использую в `BuilderIngredientsSelector.vue`

2021-07-13 17:26 UTC, Djaler commented on src/frontend/src/common/components/AppRadio.vue
> +export default {
Да, действительно, прозевал, извиняюсь

2021-07-14 17:45 UTC, corvus-007 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              :value="fillingsCounterList[index].count"
Мне не нравится вот такое решение - передаю объект, через индекс другого массива. Чувствую, что есть вариант лучше, но не знаю какой ))

2021-07-14 21:38 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              :value="fillingsCounterList[index].count"
я бы вместо fillingsCounterList (который по сути дублирует fillingsList + дополнительное поле count у каждого элемента) держал в Index.vue и передавал бы сюда объект, у которого ключ - это filling.value, а значение - count. Тогда тут в AppCounter будет что-то вроде `:value="fillingCounts[fillingItem] || 0"`

2021-07-14 21:40 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              :value="fillingsCounterList[index].count"
Всё остальное вроде норм

2021-07-15 18:21 UTC, merged